name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env: 
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4
      - name: Show repo files
        run: ls -la
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Show Hello World
        run: npm run hello-world
      - name: Lint source code with eslint
        run: npm run lint